### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by thetlwinaung** [makemoji/MakemojiSDK-Android#1]
Who To make Asop Keyboard popup windos.

**Comment by sbaar** [comment]
I don't understand the question. Can you post a screenshot of the desired behavior you're looking for?

**Comment by KstKeyboard** [comment]
@Override
    public View onCreateInputView() {


        KstKeyboardView inputView = (KstKeyboardView)
                super.onCreateInputView();
        inputView.setOnKeyboardActionListener(this);
        mDistinctMultiTouch = inputView.hasDistinctMultitouch();

        return inputView;
    }
