### ISSUE TITLE
Keyboard Hang Issue

### ISSUE THREAD

**Issue by vinod-morya** [makemoji/MakemojiSDK-Android#3]
I am testing the app on galaxy note 2, i noticed that the keyboard hangs more often you type because the trending search section keeps changing as per the context in the edittext. Please focus on the optimization of the process and resolve the issue.
Also please add a feature to just disable and enable the trending search feature in the next SDK release.

**Comment by sbaar** [comment]
I want to make sure we're on the same page. This weekend I fixed an issue that was causing a lot of work to be done on each letter typed. Does this issue persist on the latest version, 813?

**Comment by sbaar** [comment]
I'm going to take another look at this issue. I improved the performance but it's still not where it should be.

**Comment by sbaar** [comment]
Fixed in 814

**Comment by vinod-morya** [comment]
Thanks @sbaar for quick resolution.
