### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by TheBachelor** [makemoji/MakemojiSDK-Android#4]
How can I go about using the **ReactionsLayout** in a **RecyclerView Adapter**? I want to get the **reactionData** each time a **reaction** is selected for each row in the RecyclerView. 

I can't seem to find a way to send the index I'm at in the adapter when the **add** button is clicked on the **ReactionsLayout**

**Comment by sbaar** [comment]
To get the add button to work properly, you just need to add 

`    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        ReactionsData.onActivityResult(requestCode,resultCode,data);
    }`

to your activity. If you want to know when an individual item in a reactionlayout is clicked, I'll have to add that callback.

**Comment by TheBachelor** [comment]
Already done, It's working properly. 
Yeah a callback would be **greatly appreciated**
